# Generated by Django 4.2.1 on 2023-05-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producto_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=30)),
                ('confirmarcontraseña', models.CharField(max_length=30)),
            ],
        ),
    ]
