# Generated by Django 4.2.1 on 2023-05-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_suscripcion_delete_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
