# Generated by Django 4.2 on 2023-05-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='fechavencimiento',
            field=models.DateField(),
        ),
    ]
