# Generated by Django 4.2 on 2023-05-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_producto_precio_alter_producto_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
