# Generated by Django 4.2 on 2023-05-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_itemcarrito_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
