# Generated by Django 4.2.1 on 2023-05-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fechagregado',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fechamodificado',
            field=models.DateField(null=True),
        ),
    ]
