# Generated by Django 4.2 on 2023-06-01 00:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_producto_fechagregado_producto_fechamodificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='fecha_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
