# Generated by Django 4.2 on 2023-06-01 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_historial_producto_historial_compras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='historial_compras',
        ),
        migrations.AddField(
            model_name='producto',
            name='historial_compras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.historial'),
        ),
    ]
